#!/usr/bin/env python3
"""
Haberdash Build System
Bundles modular CSS and generates HTML pages from components
"""

import os
import json
from pathlib import Path

# Paths
ROOT = Path(__file__).parent
LIB_DIR = ROOT / 'lib'
COMPONENTS_DIR = ROOT / 'components'
DIST_DIR = ROOT / 'dist'

def ensure_dist():
    """Create dist directory if it doesn't exist"""
    DIST_DIR.mkdir(exist_ok=True)
    print(f'✓ Created {DIST_DIR}')

def bundle_css():
    """Bundle all CSS files into a single stylesheet"""
    css_parts = []

    # Header
    css_parts.append('/*')
    css_parts.append(' * Haberdash - Modular Component System')
    css_parts.append(' * Generated by build.py')
    css_parts.append(' */')
    css_parts.append('')

    # 1. Load global styles (lib/)
    lib_files = ['tokens.css', 'base.css', 'utilities.css']
    for filename in lib_files:
        file_path = LIB_DIR / filename
        if file_path.exists():
            css_parts.append(f'/* ========== {filename.upper()} ========== */')
            css_parts.append(file_path.read_text())
            css_parts.append('')
            print(f'  ✓ Loaded lib/{filename}')

    # 2. Load component styles (components/*/*.css)
    for component_dir in sorted(COMPONENTS_DIR.iterdir()):
        if not component_dir.is_dir():
            continue

        css_file = component_dir / f'{component_dir.name}.css'
        if css_file.exists():
            css_parts.append(f'/* ========== COMPONENT: {component_dir.name.upper()} ========== */')
            css_parts.append(css_file.read_text())
            css_parts.append('')
            print(f'  ✓ Loaded component: {component_dir.name}')

    # 3. Write bundled CSS
    output_file = DIST_DIR / 'haberdash.css'
    output_file.write_text('\n'.join(css_parts))

    print(f'✓ Bundled CSS → {output_file}')
    return output_file

def get_components():
    """Get list of all components with their metadata"""
    components = []

    for component_dir in sorted(COMPONENTS_DIR.iterdir()):
        if not component_dir.is_dir():
            continue

        html_file = component_dir / f'{component_dir.name}.html'
        meta_file = component_dir / f'{component_dir.name}.meta.json'

        if html_file.exists():
            component = {
                'name': component_dir.name,
                'html': html_file.read_text(),
                'meta': {}
            }

            if meta_file.exists():
                component['meta'] = json.loads(meta_file.read_text())

            components.append(component)
            print(f'  ✓ Loaded component: {component_dir.name}')

    return components

def generate_index(components):
    """Generate index.html showcase page"""
    html_parts = []

    html_parts.append('<!DOCTYPE html>')
    html_parts.append('<html lang="en">')
    html_parts.append('<head>')
    html_parts.append('  <meta charset="UTF-8">')
    html_parts.append('  <meta name="viewport" content="width=device-width, initial-scale=1.0">')
    html_parts.append('  <title>Haberdash - Component Showcase</title>')
    html_parts.append('  <link rel="stylesheet" href="haberdash.css">')
    html_parts.append('</head>')
    html_parts.append('<body>')
    html_parts.append('  <div class="loaded-content visible" id="content">')

    # Add each component
    for component in components:
        html_parts.append(f'    <!-- {component["name"].title()} Section -->')
        html_parts.append('    <section>')
        html_parts.append(f'      <h2>{component["meta"].get("name", component["name"].title())}</h2>')
        html_parts.append(component['html'])
        html_parts.append('    </section>')
        html_parts.append('')

    html_parts.append('  </div>')
    html_parts.append('</body>')
    html_parts.append('</html>')

    output_file = DIST_DIR / 'index.html'
    output_file.write_text('\n'.join(html_parts))

    print(f'✓ Generated index.html → {output_file}')
    return output_file

def main():
    """Main build process"""
    print('🎨 Building Haberdash...\n')

    # Ensure dist directory exists
    ensure_dist()
    print()

    # Bundle CSS
    print('📦 Bundling CSS...')
    bundle_css()
    print()

    # Get components
    print('🧩 Loading components...')
    components = get_components()
    print()

    # Generate pages
    print('📄 Generating pages...')
    generate_index(components)
    print()

    print('✅ Build complete!')
    print(f'\n📂 Output: {DIST_DIR}/')
    print(f'   - haberdash.css')
    print(f'   - index.html')

if __name__ == '__main__':
    main()
